In [13]:
with open('lspd.txt', 'r', encoding='utf-8') as f:
    text = f.read()

print("length of dataset in characters: ", len(text))
print(text[:500])

length of dataset in characters:  119162
नछाडी जानोस् हे मेरा प्राण ! अकेली मलाई,
मनको वनमा ननिभ्ने गरी विरह जलाई !
ननिभ्ने गरी विरह जलाई,
लोचनका तारा ! हे मेर प्यारा ! यो जोति  बिलाए !
के भनूँ? भन्ने म केही थिइन  विष नै पिलाए !
प्यारा ! विष नै पिलाए !
मनको कुरा गलामा अड्छ, अड्कन्छ गलामा,
यो मेरो मुटु पचासबाजी धड्कन्छ पलामा ।
यो छाती मेरो चिरेर खोली नजर गराए,
त्यो मन केही फर्कंदो होला, तस्विर खुलाए
आँसुमा खस्छ मनको टुक्रा यो आँसु बोल्दैन,
मनको कुरा मनमै बस्छ, छातिले खोल्दैन,
प्यारा ! आँसुले बोल्दैन !
हे मेरी मुना ! नभन त्यसो, जूनमा फुल


In [14]:
len(text)

119162

In [15]:
print(text[:1000])

नछाडी जानोस् हे मेरा प्राण ! अकेली मलाई,
मनको वनमा ननिभ्ने गरी विरह जलाई !
ननिभ्ने गरी विरह जलाई,
लोचनका तारा ! हे मेर प्यारा ! यो जोति  बिलाए !
के भनूँ? भन्ने म केही थिइन  विष नै पिलाए !
प्यारा ! विष नै पिलाए !
मनको कुरा गलामा अड्छ, अड्कन्छ गलामा,
यो मेरो मुटु पचासबाजी धड्कन्छ पलामा ।
यो छाती मेरो चिरेर खोली नजर गराए,
त्यो मन केही फर्कंदो होला, तस्विर खुलाए
आँसुमा खस्छ मनको टुक्रा यो आँसु बोल्दैन,
मनको कुरा मनमै बस्छ, छातिले खोल्दैन,
प्यारा ! आँसुले बोल्दैन !
हे मेरी मुना ! नभन त्यसो, जूनमा फुलेकी !
फर्कन्छु फेरि म चाँडै भन्ने किन हो भुलेकी ?
म बीसै दिन बसुँला ल्हासा, बाटामा बीसै दिन्,
चखेवा फेरी आउँछ उडी बिहान कुनै दिन्,
प्यारी ! भेटको बडा दिन !
कि मरिछाड्यो, कि गरिछाड्यो मर्दको इरादा,
नहाल प्यारि ! बाटामा मेरो आँसुको यो बाधा ।
अनार दाना दाँतका लहर खोलेर हाँसन्,
तिमीले हाँसे म हाँक्न सक्छु ईन्द्रको आसन ।
प्यारी ! बिदामा हाँसन 
हे मेरा राम ! हे मेरा कृष्ण ! जङ्गल, पहाड,
भीरका भोटे, वनका जन्तु, गाइको आहार !
रातमा सुर्जे, बिदामा हाँसो कसरी मिलाऊँ ?
हजुरको गाथ, हजुरको माथ प्रीतिले समाऊँ 

In [16]:
chars = sorted(list(set(text)))
vocab_size = len(chars)

In [17]:
print("".join(chars))
print(vocab_size)


 !,.:;?ँंःअआइईउऊऋएऐओऔकखगघङचछजझञटठडढणतथदधनपफबभमयरलवशषसहािीुूृेैोौ्ॐ।‍–‘’“”
74


In [19]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

# test it
print(encode("नेपाल"))
print(decode(encode("नेपाल")))


 !,.:;?ँंःअआइईउऊऋएऐओऔकखगघङचछजझञटठडढणतथदधनपफबभमयरलवशषसहािीुूृेैोौ्ॐ।‍–‘’“”
74
[41, 61, 42, 55, 49]
नेपाल


In [20]:
import torch

data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:100])  # first 100 chars as numbers



torch.Size([119162]) torch.int64
tensor([41, 28, 55, 34, 57,  1, 29, 55, 41, 63, 53, 65,  1, 54, 61,  1, 46, 61,
        48, 55,  1, 42, 65, 48, 55, 36,  1,  2,  1, 11, 22, 61, 49, 57,  1, 46,
        49, 55, 14,  3,  0, 46, 41, 22, 63,  1, 50, 41, 46, 55,  1, 41, 41, 56,
        45, 65, 41, 61,  1, 24, 48, 57,  1, 50, 56, 48, 54,  1, 29, 49, 55, 14,
         1,  2,  0, 41, 41, 56, 45, 65, 41, 61,  1, 24, 48, 57,  1, 50, 56, 48,
        54,  1, 29, 49, 55, 14,  3,  0, 49, 63])


In [21]:
# split: 90% train, 10% validation
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

print(f"\nTrain size: {len(train_data)} characters")
print(f"Val size:   {len(val_data)} characters")


Train size: 107245 characters
Val size:   11917 characters


In [23]:
block_size = 10
train_data[:block_size+1]

tensor([41, 28, 55, 34, 57,  1, 29, 55, 41, 63, 53])

In [24]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([41]) the target: 28
when input is tensor([41, 28]) the target: 55
when input is tensor([41, 28, 55]) the target: 34
when input is tensor([41, 28, 55, 34]) the target: 57
when input is tensor([41, 28, 55, 34, 57]) the target: 1
when input is tensor([41, 28, 55, 34, 57,  1]) the target: 29
when input is tensor([41, 28, 55, 34, 57,  1, 29]) the target: 55
when input is tensor([41, 28, 55, 34, 57,  1, 29, 55]) the target: 41
when input is tensor([41, 28, 55, 34, 57,  1, 29, 55, 41]) the target: 63
when input is tensor([41, 28, 55, 34, 57,  1, 29, 55, 41, 63]) the target: 53


In [26]:
torch.manual_seed(1000)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[55,  1, 42, 58, 48, 59, 52,  1],
        [ 0, 27, 55, 46, 49,  1, 18, 22],
        [ 1, 24, 48, 65, 28, 64,  1, 45],
        [41, 57,  1, 53, 55, 22, 55, 48]])
targets:
torch.Size([4, 8])
tensor([[ 1, 42, 58, 48, 59, 52,  1, 54],
        [27, 55, 46, 49,  1, 18, 22,  1],
        [24, 48, 65, 28, 64,  1, 45, 55],
        [57,  1, 53, 55, 22, 55, 48,  3]])
----
when input is [55] the target: 1
when input is [55, 1] the target: 42
when input is [55, 1, 42] the target: 58
when input is [55, 1, 42, 58] the target: 48
when input is [55, 1, 42, 58, 48] the target: 59
when input is [55, 1, 42, 58, 48, 59] the target: 52
when input is [55, 1, 42, 58, 48, 59, 52] the target: 1
when input is [55, 1, 42, 58, 48, 59, 52, 1] the target: 54
when input is [0] the target: 27
when input is [0, 27] the target: 55
when input is [0, 27, 55] the target: 46
when input is [0, 27, 55, 46] the target: 49
when input is [0, 27, 55, 46, 49] the target: 1
when input is [0, 27, 55

In [27]:
print("4 input sequences decoded:")
for i in range(4):
    print(f"Batch {i}: {decode(xb[i].tolist())}")

4 input sequences decoded:
Batch 0: ा पुरूष 
Batch 1: 
चामल एक
Batch 2:  गर्छौ भ
Batch 3: नी साकार


In [28]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        logits = self.token_embedding_table(idx)  # (B, T, C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, loss = self(idx)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print("logits shape:", logits.shape)
print("initial loss:", loss.item())

# generate some text before training (will be garbage)
context = torch.zeros((1, 1), dtype=torch.long)
print("\nGenerated text before training:")
print(decode(m.generate(context, max_new_tokens=100)[0].tolist()))

logits shape: torch.Size([32, 74])
initial loss: 4.78005838394165

Generated text before training:

हो‍म;अँ,ःई’”र।“भ।ुंरीरीफेंब्‘णङकौृहशलह.।ओढठगवषारठआ;ृकघठुॐलक?झच,ङड’य––नधंम’ॐञूशछघ।शभऊवऐछऔढँगौहझाष ढौश


In [29]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [31]:
batch_size = 32
for steps in range(10000): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


2.699967861175537


In [32]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


छ
रोलिकलें प्रनाई  जर छः आतल छे लाझिँ परोरी, य पतिनि स्थरा सेहा !
को घु हि शी !
हने ना श्टाई घ!
“आमी गुत गुनकि बुहिन्छो नेर रिरङ्वनौ अनानिल्रुखुल्चिलो,
केकुकामानिवीरव भटुल्वपहाल्र माकर वी को !
साल बिललनिडगताराबा कल  फिले, !
सिदछ, छावरङ्नेश् आँछै कुराटीम !
यो उँचोको, दुकानकिधाबिनिन्र् ने गरफुषकेर मा चिर आपी हा ! बिन्यघुन्छ,
“मज–म्गडेकोसुइ त्द्र हपरेला काको म्रुण देँ,
मूकेक् कान दा
शको, !
ह्य ! र्दाग ! डू केपनको, कलशीतोलकोएकासमागु !
अम्रीठधिन्,
धनलानेर्ताथेकुँचले, पिं
इर्छन–आता हुखी लेर्छ !
अनै छा


In [33]:
# Mathmatical Trick Behind Self Attention

In [34]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [35]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1]  # (t+1, C)
        xbow[b,t] = torch.mean(xprev, 0)

print(x[0])
print(xbow[0])

tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643],
        [ 0.3612,  1.1679],
        [-1.3499, -0.5102],
        [ 0.2360, -0.2398],
        [-0.9211,  1.5433]])
tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])


In [37]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x  # (T,T) @ (B,T,C) --> (B,T,C)
print(wei)
torch.allclose(xbow, xbow2, atol=1e-6)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])


True

In [38]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
print(wei)
wei = F.softmax(wei, dim=-1)
print(wei)
xbow3 = wei @ x
torch.allclose(xbow, xbow3, atol=1e-6)

tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])


True

In [40]:
torch.manual_seed(1337)
B,T,C = 4,8,32
x = torch.randn(B,T,C)

head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)

k = key(x)
q = query(x)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

tril = torch.tril(torch.ones(T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v

print(out.shape)
print(wei[0])  # show attention weights for first batch

torch.Size([4, 8, 16])
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3966, 0.6034, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3069, 0.2892, 0.4039, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3233, 0.2175, 0.2443, 0.2149, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1479, 0.2034, 0.1663, 0.1455, 0.3369, 0.0000, 0.0000, 0.0000],
        [0.1259, 0.2490, 0.1324, 0.1062, 0.3141, 0.0724, 0.0000, 0.0000],
        [0.1598, 0.1990, 0.1140, 0.1125, 0.1418, 0.1669, 0.1061, 0.0000],
        [0.0845, 0.1197, 0.1078, 0.1537, 0.1086, 0.1146, 0.1558, 0.1553]],
       grad_fn=<SelectBackward0>)


In [41]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

print(k.var())
print(q.var())
print(wei.var())

tensor(1.0449)
tensor(1.0700)
tensor(1.0918)


In [43]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16
block_size = 32
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0

torch.manual_seed(1337)

# CHANGED: load Nepali text instead of Shakespeare
with open('lspd.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# unique characters
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(f"vocab size: {vocab_size}")

stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

# train/val split
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)
        q = self.query(x)
        wei = q @ k.transpose(-2,-1) * C**-0.5
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        v = self.value(x)
        out = wei @ v
        return out

class MultiHeadAttention(nn.Module):
    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    def __init__(self, n_embd, n_head):
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

class GPTLanguageModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        tok_emb = self.token_embedding_table(idx)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device))
        x = tok_emb + pos_emb
        x = self.blocks(x)
        x = self.ln_f(x)
        logits = self.lm_head(x)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -block_size:]
            logits, loss = self(idx_cond)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)
        return idx

# CHANGED: renamed to GPTLanguageModel
model = GPTLanguageModel()
m = model.to(device)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    xb, yb = get_batch('train')
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))

vocab size: 74
0.21089 M parameters
step 0: train loss 4.4213, val loss 4.4307
step 100: train loss 2.8552, val loss 2.9087
step 200: train loss 2.7601, val loss 2.8276
step 300: train loss 2.7089, val loss 2.7786
step 400: train loss 2.6719, val loss 2.7599
step 500: train loss 2.6284, val loss 2.7314
step 600: train loss 2.6037, val loss 2.7037
step 700: train loss 2.5650, val loss 2.6638
step 800: train loss 2.5269, val loss 2.6371
step 900: train loss 2.5108, val loss 2.6208
step 1000: train loss 2.4797, val loss 2.5886
step 1100: train loss 2.4445, val loss 2.5728
step 1200: train loss 2.4219, val loss 2.5579
step 1300: train loss 2.3990, val loss 2.5466
step 1400: train loss 2.3900, val loss 2.5285
step 1500: train loss 2.3583, val loss 2.5095
step 1600: train loss 2.3493, val loss 2.4907
step 1700: train loss 2.3218, val loss 2.4794
step 1800: train loss 2.3066, val loss 2.4812
step 1900: train loss 2.2927, val loss 2.4471
step 2000: train loss 2.2764, val loss 2.4630
step 2100: